# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shimesukun_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    networks:
      - shimesukun_network

  db:
    image: mysql:8.0
    container_name: shimesukun_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shimesukun
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: shimesukun
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - shimesukun_network

  nginx:
    image: nginx:alpine
    container_name: shimesukun_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - shimesukun_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shimesukun_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - shimesukun_network

networks:
  shimesukun_network:
    driver: bridge
